---
title: "Takım: Ançüez"
sidebar: false 
---

MUY665-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu sitede dönem boyu olan çalışmalarımızı paylaşıyor olacağız.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

1.  [Kerem Asaf Tecirlioğlu](/takim/kerem.qmd)

2.  [Özgür Adıgüzel KAYA](/takim/ozgur.qmd)

3.  [Büşra Bahar KURT](/takim/bbaharkurt.qmd)

4.  Muhammed Said AKÇAY

## Proje Adı

Türkiye’de Taşıt Sahipliği ve Kullanımı: Veriler ve Eğilimler

## Proje Konusu

Projemiz Türkiye'deki araç demografini incelemek ve bu konular hakkında faydalı çıkarımlar yapabilmek. Bunlar arasında gelecek projeksiyonları, anlık durum, anlık durumun trend eğrileri gibi grafikler yer almakta. Sağlanan veriler ve medya sayesinde yapılabilecek iyileştirmeler, gelecekte sektörel anlamda ne gibi yönlere gidilebileceği ve nüfusün otomotiv alımı ve sahipliğinde ne gibi bir rol oynadığını inceledik.

## Veri Seti Hakkında Özet Bilgi

Türkiye'de türlerine göre (otomobil,kamyon vb.) kara taşıtı sayıları, illere göre toplam kara taşıtı sayıları ve yakıt türlerine göre toplam kara taşıtı sayılarının yıllar içindeki değişimini gösteren veri setlerini kullanarak analizlerimizi yaptık.

## Sonuçlar

-   **Motorlu Kara Taşıtları:** TÜİK'in 2023-2024 verilerine göre, Türkiye'de motorlu kara taşıtlarının toplam sayısında önemli bir artış görülmüştür. Bu anlamda otomobiller, kamyonetler ve motosikletler özellikle dikkat çekmektedir. Ekonomideki iyileştirmeler ve uygun kredi koşulları, otomobil sayısının artmasına neden olabilir. Ticaret ve lojistik sektörlerindeki büyüme, motosiklet ve kamyonet sayısının artmasına neden olabilir. Genel trend, gelecekte motorlu taşıt sayısının artmaya devam edeceğini göstermektedir.

-   **Elektrikli Araçlar:** Türkiye, elektrikli araç kullanımı trendinde diğer Avrupa ülkelerine göre geride kalmıştır. 2022 yılında satılan araçların %90'ının petrol türevli yakıtlı araçlardan oluşması bu durumu açıkça göstermektedir. Ancak, tahmin modelleri, elektrikli araç sayısında önümüzdeki yıllarda önemli bir artış yaşanacağını öngörmektedir. Bu artış, teşvik politikaları, artan çevre bilinci ve teknolojideki gelişmelerin etkisiyle hızlanacaktır. Dolayısıyla, Türkiye'nin elektrikli araç pazarında gelecekteki büyüme potansiyeli oldukça yüksektir.
