---
title: "Çalışma 1"
---

Bu çalışmada 3 görevimiz var. Bu görevler,

## (a) Sağlanan kaynak videolardan özet sağlamak

-   Videonun 30-60. dakikası özeti:

------------------------------------------------------------------------

> \<div class='text-justify'\>
>
> Geleneksel öğrenme ve derin öğrenme süreçleri karşılaştırıldığında geleneksel öğrenmede öznitelik çıkarımları yapılırken ciddi çalışmalar yapılıp, veriler toplanıp işlenirken, derin öğrenme sürecinde öznitelik çıkarımı ve öğrenme kısmı kendi içinde dahil olduğu için geleneksel öğrenmede bu tarafta daha fazla efor harcanıyor. Kıyaslamaya bakıldığında yapısal olmayan verilerde derin öğrenme daha iyi çalışmakta. Ancak yorumlanabilirliği daha düşük. Aynı zamanda robust açısından değerlendirildiğinde kullanılan tahmin yöntemi sonucunda bir tahminin yanlış olması durumunda sistemin etkilenme oranı derin öğrenmede daha fazla.
>
> Tahmin yöntemlerinin kullanılmasının en önemli sebebi karar vermede bu yöntemlerin etkili olması. Tahmin doğruluğunun önemi çeşitli örnekler verilerek anlatılmakta. Elektrik piyasasındaki örnekte olduğu gibi saatlik elektrik üretim ve tüketim miktarlarındaki yanlış tahminler yıllık bakıldığında şirketler için ciddi miktarda maddi kayıplara sebep olmakta. Çeşitli özelleşmiş öznitelik çıkarımları ve makine öğrenimi kullanarak oluşturulan modeller ile bu kayıplar da aynı zamanda ciddi oranda azaltılabilir. Bu modeller oluşturulurken doğru verilen toplanması ve özel durumlarda bu verilerin sürekli olmayabileceğinin de göz önünde bulundurulması gerekiyor.
>
> Online satış sitelerinde verilen örnekte ise sıralama önceliklerine ve cironun artırılması için alternatif yaklaşımlara değinilmekte. Satış/Stok dengesi ve popülerlik gibi görece basit yöntemlerle insanların önüne çıkan ürünler şirketlerin kazancını artırabilir. Makine öğrenimi kullanımında ise benzetme, tercih öğrenme ve tahmini satış gibi yaklaşımlar bulunmakta. Bu yaklaşımlar satış oranıyla çift yönlü bir etkileşimde olduğu için taraflı veri (bias) olarak değerlendirilir. Pekiştirmeli öğrenme yönteminde ise akıllı deneme yanılma yaklaşımı kullanılabilir. Bir A algoritmasını denemek isteyelim. Bu algoritmayı 1-2 saatliğine sitede çalıştırırken arka tarafta ise halihazırda güvenilen B algoritması çalıştırılarak A algoritmasının satışa etkisi denenebilir. Burada geçmişte öğrenilen bilgilerle makine öğreniminde kullanılan satranç oynayan makineler örneği de veriliyor. Basit sıralama politikasında da ürünlerin kullanıcı için bir dinamik skoru bulunuyor. Bu yöntemde çok fazla bakılan ürünler taraflılıktan kurtulmak açısından bir katsayıyla cezalandırılıyor.
>
> Sonraki örnekte ise tahmin yöntemleri kullanılırken belirli fiziksel yasaların da bu tahmin algoritmalarında etkin şekilde kullanılmasının öneminden bahsediliyor. Örneğin bir hava durumu tahmini yapılacaksa kütlenin korunumu gibi bir fiziksel yasa kullanılmadan tahmin yapılması çok mantıklı olmayacak. Bu şekilde fizik kurallarının da algoritmalara eklenmesiyle beraber tahminlerin doğruluğu artırılabilir.
>
> Optimizasyon yöntemlerinin kullanımında örneğin envanter yönetimi gibi süreçlerde, talep tahmini ve lojistik planlama gibi konuların nasıl matematiksel modeller ve optimizasyon yöntemleri kullanılarak çözülebileceğine dair açıklamalar bulunulmuştur. Aynı zamanda belirli bir zaman diliminde belirli miktarlarda ürünün belirli noktalara ulaştırılması gibi karmaşık kararlar almak için bu tür yöntemlerin nasıl uygulanabileceği üzerinde durulmuştur. Makine öğrenimi ile optimizasyonun birleştirilmesi için geçmişte çözülmüş optimizasyon problemlerinden elde edilen verilerin, makine öğrenimi algoritmalarıyla analiz edilerek gelecekteki optimizasyon problemlerine nasıl uygulanabileceği tartışılmıştır. Makine öğrenimi ve optimizasyonun birleştirilmesinin, karmaşık karar verme süreçlerini otomatikleştirmek ve iyileştirmek için nasıl kullanılabileceği konusunda daha fazla araştırma ve geliştirme yapılması gerektiği üzerinde durulmuştur.
>
> Videonun son bölümünde gelen sorulara göre bazı konular üzerinde durulmuştur. Veri analizi becerilerini geliştirmek için lisans eğitimi sırasında gerçek dünya problemleri üzerinde çalışmak oldukça değerlidir. Öğrenciler, endüstriyel projeler veya akademik araştırmalar kapsamında veri toplayıp, temizleyip, analiz edip ve yorumlayabileceğine değinilmiştir. Ayrıca cesaretli davranmak, kendi ilgi alanlarına odaklanmak ve bu alanda uygulama yapmak önemlidir. Farklı veri analizi tekniklerini denemek ve çeşitli veri setleri üzerinde çalışmak geniş bir perspektif kazandırabilir. Kaggle gibi platformlarda düzenlenen veri analizi yarışmalarına katılmak, öğrencilere gerçek dünya veri setleriyle çalışma ve problem çözme becerilerini geliştirme fırsatı sunmaktadır.
>
> Computer vision alanında çalışmak isteyen öğrenciler, görüntü işleme ve derin öğrenme teknikleri üzerine odaklanabileceği söylenmiştir. PyTorch gibi derin öğrenme kütüphanelerini kullanarak yapay sinir ağı modelleri oluşturmak ve eğitmek, öğrencilere derin öğrenme konusunda pratik deneyim kazandırabileceği konuşulmuştur.
>
> \</div\>

------------------------------------------------------------------------

## (b) Özel fonksiyonlar ve döngüler ile istatistiksel özetleri keşfetmek

```{r}
custom_summary <- function(vector){
    mean <- mean(vector)
    median <- median(vector)
    min <- min(vector)
    max <- max(vector)
    sd <- sd(vector)
    return(c(mean, median, min, max, sd))
}


{
  print("Mean, Median, Min, Max, SD")
  for (param in 1:length(mtcars)) {
      print(custom_summary(mtcars[,param]))
  }
}

apply(mtcars, 2, custom_summary)
```

## (c) Vektör verilerini aramak ve kullanmak

```{r}
library("dslabs")

buf = na_example

print(buf)


counter = 0

for (param in 1:length(buf)) {
	if(is.na(buf[param])){
		buf [param] = 665
		counter = counter + 1

	}
	
}


{
	format = sprintf("Number of NA variables in na_example vector is %d", counter)
	print(format)
	print(buf)
}

```
